server {
    listen 80;
    server_name 200.137.132.131;

    # --- ROTA 1: PORTAINER ---
    location /portainer/ {
        # Mudamos de IP para o nome direto do container na rede compartilhada
        proxy_pass https://portainer:9443/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cookie_path / /portainer/;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location = /portainer {
        return 301 $scheme://$http_host/portainer/;
    }
    # --- ROTA 2: API LATTES (200.137.132.131/api-lattes) ---
    # location /api-lattes/ {
    #     # Aponta para o nome do container e a porta interna informada
    #     proxy_pass http://api-lattes:6500/;
        
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     # Garante que os cookies da API respeitem o caminho da subpasta
    #     proxy_cookie_path / /api-lattes/;
    # }
    # Redireciona automaticamente se o usuario esquecer a barra no final de /api-lattes
    # location = /api-lattes {
    #     return 301 $scheme://$http_host/api-lattes/;
    # }

    # ROTA 3: SIDPB FRONTEND 
    location /sidpb/ {
        proxy_pass http://sidpb_frontend:3000/;
        proxy_http_version 1.1;
        proxy_redirect default;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Prefix /sidpb; 
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location = /sidpb {
        proxy_pass http://sidpb_frontend:3000/;
    }

    # SIDPB API
    location /sidpb/api/ {
        proxy_pass http://sidpb_backend:8080/api/;
        proxy_redirect default;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Prefix /sidpb; 
        proxy_set_header X-Forwarded-Proto $scheme;

        # CORS para o frontend
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Headers 'Content-Type, Authorization' always;
        add_header Access-Control-Allow-Methods 'GET,POST,PUT,DELETE,OPTIONS' always;
        if ($request_method = OPTIONS) {
            return 204;
        }
    }
    location = /sidpb/api {
        return 301 $scheme://$http_host/sidpb/api/;
    }

    # ROTA 4: Cultura Maranhense
    location /cultura/ {
        proxy_pass http://cultura-maranhense:3000;
        proxy_http_version 1.1;
        proxy_redirect default;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Prefix /cultura;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    location = /cultura {
        proxy_pass http://cultura-maranhense:3000;
    }
    # --- ROTA geral: SITE NCA-UFMA ---
    location / {
        proxy_pass http://github.io;
        proxy_set_header Host ncaufma.github.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}