spring.application.name=sidpb-backend
spring.datasource.url=jdbc:postgresql://db:5432/db_sidpb
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate is disabled because Flyway will manage schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.type.json_format_mapper=jackson

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration