spring.datasource.url=${TEST_DB_URL:jdbc:postgresql://localhost:5432/parasitologia_test}
spring.datasource.username=${TEST_DB_USERNAME:postgres}
spring.datasource.password=${TEST_DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.type.json_format_mapper=jackson
